### PR TITLE
+ Added Monad Transformer for Twitter Future and Scalactic Or

### PR DESCRIPTION
**Pull request by forthy**
Scalactic provides a very power design: Or. Or can be a replacement of `Either` type and accumulates error types.
With this addition, hamster can provide a Monad Transformer for Twitter Future and Scalactic Or.

http://www.scalactic.org

### CODE REVIEW

**Comment by loicdescotte** [comment]
Hi,
Hamsters already provides some OK/KO to represent Good/Bad.  
As a hamsters extension Twitter Future should rely on this.  
But you can also provide a Scalactic Or extension, in addition to Twitter Future extension.
Can you update the PR in this way?

Thanks

**Comment by forthy** [comment]
Like Hamsters HList extensions? Shall do! 👍

**Comment by loicdescotte** [comment]
Yes! ;)

**Comment by dgouyette** [comment]
This PR should be closed ?

**Comment by loicdescotte** [comment]
@dgouyette indeed

**Pull request closed without merging**
